### ISSUE TITLE
Please add Support for 1.19

### ISSUE THREAD

**Issue by CloudeLecaw** [Arthed-Plugins/CustomBiomeColors#5]
On the new spigot 1.18.2 the plugin freused to load.
And throw annlittle error innconsole.
It would be nice to have a little Update for this.

A little talk woth other devs, they said the updating to 1.18.2 is no big deal this time :)

**Comment by Wolvend** [comment]
@CloudeLecaw My friend updated unofficially to 1.19. You can find it under pull requests

**Comment by CloudeLecaw** [comment]
I see the Version 1.2.0 
But how can i get it?
Do need to compile this myswlf?

**Comment by Wolvend** [comment]
[https://drive.google.com/file/d/1UpZifhza-MI36cJXZQSiR3fZwVYuK7Fj/view?usp=sharing](url)
Here is the compiled .jar if you'd like

**Comment by CloudeLecaw** [comment]
> [https://drive.google.com/file/d/1UpZifhza-MI36cJXZQSiR3fZwVYuK7Fj/view?usp=sharing](url) Here is the compiled .jar if you'd like

im comfues about the link? it leads me to
![image](https://user-images.githubusercontent.com/12080017/176986225-a06c7698-347e-4df3-9310-11dadbf0eba7.png)

**Comment by CloudeLecaw** [comment]
well found the issue it was showing
[https://drive.google.com/file/d/1UpZifhza-MI36cJXZQSiR3fZwVYuK7Fj/view?usp=sharing](https://github.com/Arthed-Plugins/CustomBiomeColors/issues/url)

but the github was linking me to other site.
So Copy the URL into clipboard (STRG + C) and paste it in addressbar works
